development: &development
  adapter: redis
  url: redis://redistogo:3323b1b0471cc3522fa209165403c1c7@porgy.redistogo.com:10116/

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: blog_production
