development:
  forest_env_secret: e2d75fe35724630dd587c69b86353d9df004878dd099ced261b1bbfed6d98155
  forest_auth_secret: P-5zqd_V-1Lm65Uo8MRBPw
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
